blogs/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'), # 목록
    path('<int:post_id>/', views.detail, name='detail'), #상세 페이지
    path('post/create/', views.post_create, name='post_create'),
    path('category/<str:slug>/', views.category_page,
            name='category_page'), # 카테고리별 페이지
    path('post/delete/<int:post_id>/', views.post_delete,
            name='post_delete'),   # 포스트 삭제
    path('comment/create/<int:post_id>/', views.comment_create,
            name='comment_create'), # 댓글 등록
    path('comment/delete/<int:comment_id>/', views.comment_delete,
            name='comment_delete'), # 댓글 삭제
    path('comment/modify/<int:comment_id>/', views.comment_modify,
            name='comment_modify'), # 댓글 수정
]

blogs/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html')
          , name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

blogs/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index), #http://127.0.0.1:8000/
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),    # 일반 로그인
    path('accounts/', include('allauth.urls')), # 소셜 로그인
]

urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="https://kit.fontawesome.com/187dabceeb.js"
            crossorigin="anonymous"></script> <!-- fontawesome 키트-->
    <script  src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar.html' %}
<!-- 본문 영역 -->
{% block content %}
{% endblock %}


<!-- 자바 스크립트 영역 -->
{% block script %}
{% endblock %}
</body>
</html>

blogs/templates/form_errors.html
<!-- 유효성 검사 - 오류 처리 시작-->
{% if form.errors  %}
    {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
        {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
         </div>
        {% endif %}
    {% endfor %}

    <!-- 넌 필드 오류-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- 오류 처리 끝-->

blogs/templates/navbar.html
<!-- 소셜 로그인 태그 명시 -->
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">PyBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_create' %}">글쓰기</a>
        </li>
      </ul>
      <!-- 로그인 영역 -->
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
              data-bs-toggle="dropdown">{{ user.username }}</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'common:logout' %}">로그아웃</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" data-bs-target="#loginModal"
              data-bs-toggle="modal">로그인</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<!-- 로그인 Modal -->
<div class="modal" tabindex="-1" id="loginModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><i class="fa-solid fa-right-to-bracket"></i> 로그인</h5>
        <button type="button" class="btn-close" data-dismiss="modal"
                aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <a href="{% provider_login_url 'google' %}" class="btn btn-outline-dark btn-block btn-sm mx-4">
          <i class="fa-brands fa-google"></i> Google 로그인
        </a>
        <a href="{% url 'common:login' %}"
           class="btn btn-outline-dark btn-block btn-sm">
          <i class="fa-solid fa-user"></i> ID 로그인
        </a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
                data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>